/**
 * Generates public/sitemap.xml from src/config/publicSeoRoutes.ts at build time.
 * Run: node scripts/generate-sitemap.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const SITE_ORIGIN =
  process.env.VITE_SITE_ORIGIN?.replace(/\/$/, "") || "https://apexsimtracker.com";

const routesPath = join(root, "src/config/publicSeoRoutes.ts");
const routesSource = readFileSync(routesPath, "utf8");

/** Parse PUBLIC_SEO_ROUTES array entries from the TS source (no TS compiler needed). */
function parseRoutes(source) {
  const routes = [];
  const entryRe =
    /\{\s*path:\s*"([^"]+)"\s*,\s*changefreq:\s*"([^"]+)"\s*,\s*priority:\s*([\d.]+)\s*\}/g;
  let m;
  while ((m = entryRe.exec(source)) !== null) {
    routes.push({ path: m[1], changefreq: m[2], priority: m[3] });
  }
  if (routes.length === 0) {
    throw new Error("No routes parsed from publicSeoRoutes.ts");
  }
  return routes;
}

const routes = parseRoutes(routesSource);
const lastmod = new Date().toISOString().slice(0, 10);

const urlEntries = routes
  .map((r) => {
    const loc = `${SITE_ORIGIN}${r.path === "/" ? "/" : r.path}`;
    return `  <url>
    <loc>${escapeXml(loc)}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority}</priority>
  </url>`;
  })
  .join("\n");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries}
</urlset>
`;

function escapeXml(s) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

const outPath = join(root, "public/sitemap.xml");
writeFileSync(outPath, xml, "utf8");
console.log(`Wrote ${outPath} (${routes.length} URLs, lastmod=${lastmod})`);
